specify pos and max values
jhuapl-boss/heaviside pull request #18
Opened 2024-01-08 20:29 UTC by dxenes1

This change just specifies values for `pos` and `max` in funcparserlib `State()` class initialization. These variables are used only for error tracking

https://github.com/vlasovskikh/funcparserlib/blob/master/funcparserlib/parser.py#L513

The original code was compatible only with `funcparserlib==0.3.6` or lower. This change allows the activities stack to finish building with `funcparserlib>=1.0.0`.

```python
Traceback (most recent call last):
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/bin/./cloudformation.py", line 301, in <module>
    call_configs(bosslet_config, configs, func)
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/bin/./cloudformation.py", line 201, in call_configs
    module.__dict__[func_name](bosslet_config)
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/cloud_formation/configs/activities.py", line 233, in post_init
    sfn.create(bosslet_config, name, path, role)
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/lib/stepfunctions.py", line 43, in create
    machine.create(filepath, role)
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/lib/heaviside.git/heaviside/__init__.py", line 142, in create
    definition = self.build(source)
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/lib/heaviside.git/heaviside/__init__.py", line 108, in build
    return compile(source,
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/lib/heaviside.git/heaviside/__init__.py", line 51, in compile
    machine = parse(tokens,
  File "/Users/xenesd1/Projects/BossDB/code/boss-manage/lib/heaviside.git/heaviside/parser.py", line 324, in parse
    (tree, _) = machine.run(seq, State())
TypeError: __init__() missing 2 required positional arguments: 'pos' and 'max'
```

I couldn't downgrade because funcparserlib==0.3.6 is no longer compatible with python 3.8 and above due to a PEP change.

2024-01-09 14:09 UTC, movestill requested changes
Thanks for doing this! Was planning to do it, but I still haven't needed to build my stack on my new computer yet.

Please update the CHANGELOG so it says that it now supports Python 3.8 and the new `funcparserlib` version.

2024-01-11 14:34 UTC, movestill approved these changes

2024-01-11 14:39 UTC, movestill commented
Oh, looks like this breaks for Python 3.7 due to the `setuptools` version. I _think_ we're ok dropping Python 3.7 support, @sandyhider ? If so, we should note that in the CHANGELOG and remove the tests for 3.7.

2024-01-11 15:56 UTC, dxenes1 commented
I built my dev stack on Python 3.9, but I also installed heaviside (and other boss-manage) requirements on a Python 3.8 virtualenv and it worked on my apple silicon mac!

2024-01-11 17:07 UTC, movestill commented
I thought I read that only Python 3.9 is available for Apple Silicon, but
maybe I misremembered if Danny was able to install 3.8 on his.

On Thu, Jan 11, 2024 at 10:56 AM Daniel Xenes ***@***.***>
wrote:

> I built my dev stack on Python 3.9, but I also installed heaviside (and
> other boss-manage) requirements on a Python 3.8 virtualenv and it worked on
> my apple silicon mac!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jhuapl-boss/heaviside/pull/18#issuecomment-1887468986>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYVSA6KHWK5WHAUPFNRS43YOADTVAVCNFSM6AAAAABBSA4YYSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBXGQ3DQOJYGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-19 13:39 UTC, sandyhider approved these changes

2024-03-19 18:32 UTC, merged